### ISSUE TITLE
Crash on macOS on v0.3.7

### ISSUE THREAD

**Issue by ofirmiron** [cdcsgit/lognote#12]
Seeing the following crash when launching on macOS Sonoma 14.6.1 on M1 MacBook:

```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.blogspot.cdcsutils.lognote.Main$Companion.main$lambda$0(Main.kt:16)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at com.blogspot.cdcsutils.lognote.LogTable.<init>(LogTable.kt:27)
	at com.blogspot.cdcsutils.lognote.LogPanel.<init>(LogPanel.kt:102)
	at com.blogspot.cdcsutils.lognote.MainUI.createUI(MainUI.kt:976)
	at com.blogspot.cdcsutils.lognote.MainUI.<init>(MainUI.kt:337)
	at com.blogspot.cdcsutils.lognote.MainUI.<clinit>(MainUI.kt:57)
	... 15 more
```

Note that v0.3.6 works flawlessly.

**Comment by cdcsgit** [comment]
It seems that the issue occurred fail to get the "awt.multiClickInterval" value depending on the jdk version on mac os.
https://bugs.openjdk.org/browse/JDK-7124404
I attached the LogNote.jar file that handles the exception for NullPointerException.
Please check if it works.
[LogNote-fix_mac_launch.jar.zip](https://github.com/user-attachments/files/17203439/LogNote-fix_mac_launch.jar.zip)

**Comment by ofirmiron** [comment]
That works! Thanks!

**Comment by cdcsgit** [comment]
Applied v.0.3.8.
